# Generated by Django 6.0 on 2026-01-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(max_length=50),
        ),
    ]
