# Generated by Django 6.0 on 2026-01-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_imagen_url_alter_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marca',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
