# Generated by Django 6.0 on 2026-01-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(default='', upload_to='productos/galeria/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
