# Generated by Django 6.0 on 2026-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_categoria_imagen_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blanco', models.CharField(help_text='Texto en blanco', max_length=100)),
                ('titulo_rojo', models.CharField(help_text='Texto en rojo', max_length=100)),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
