# Generated by Django 6.0 on 2026-01-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['orden'], 'verbose_name': 'Banner de Inicio', 'verbose_name_plural': 'Banners de Inicio'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(upload_to='banners/', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Posición en el slider'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo_blanco',
            field=models.CharField(help_text='Aparecerá en color blanco', max_length=100, verbose_name='Texto Superior (Blanco)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo_rojo',
            field=models.CharField(help_text='Aparecerá en color rojo', max_length=100, verbose_name='Texto inferior (Rojo)'),
        ),
    ]
