# Generated by Django 6.0 on 2026-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_banner_options_alter_banner_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='titulo_blanco',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='titulo_rojo',
        ),
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.CharField(default='/productos/', help_text='Ej: /productos/categoria/gaming/', max_length=200, verbose_name='Enlace (URL)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='texto_blanco',
            field=models.CharField(default='', max_length=100, verbose_name='Texto en Blanco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='texto_rojo',
            field=models.CharField(default='', max_length=100, verbose_name='Texto en Rojo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Posición'),
        ),
    ]
