# Generated by Django 6.0 on 2026-01-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_banner_options_remove_banner_titulo_blanco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono_emoji', models.CharField(help_text='Ej: 🛡️', max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(default='Equipamiento Pro', max_length=100)),
                ('titulo_blanco', models.CharField(default='MUNDO', max_length=100)),
                ('titulo_rojo', models.CharField(default='GAMING', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='promos/')),
                ('link_url', models.CharField(default='/', max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
