# Generated by Django 6.0 on 2026-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_beneficio_promobanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beneficio',
        ),
        migrations.AddField(
            model_name='promobanner',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='promociones', to='tienda.producto'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='slug',
            field=models.SlugField(default='', help_text='Ej: promo-verano', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='titulo_blanco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='titulo_rojo',
            field=models.CharField(max_length=100),
        ),
    ]
