# Generated by Django 6.0 on 2026-02-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_delete_beneficio_promobanner_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
